//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ProductCategoryRepositoryClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="ProductCategoryRepositoryClient.IProductCategoryRepositoryService")]
    public interface IProductCategoryRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategories" +
            "", ReplyAction="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategories" +
            "Response")]
        OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto[] GetProductCategories(System.Guid shopGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategories" +
            "", ReplyAction="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategories" +
            "Response")]
        System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto[]> GetProductCategoriesAsync(System.Guid shopGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategory", ReplyAction="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategoryRe" +
            "sponse")]
        OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto GetProductCategory(System.Guid productCategoryGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategory", ReplyAction="https://online.catalog.com/IProductCategoryRepositoryService/GetProductCategoryRe" +
            "sponse")]
        System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto> GetProductCategoryAsync(System.Guid productCategoryGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCategoryRepositoryServiceChannel : OnlineCatalog.Web.Main.ProductCategoryRepositoryClient.IProductCategoryRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCategoryRepositoryServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ProductCategoryRepositoryClient.IProductCategoryRepositoryService>, OnlineCatalog.Web.Main.ProductCategoryRepositoryClient.IProductCategoryRepositoryService {
        
        public ProductCategoryRepositoryServiceClient() {
        }
        
        public ProductCategoryRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCategoryRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto[] GetProductCategories(System.Guid shopGuid) {
            return base.Channel.GetProductCategories(shopGuid);
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto[]> GetProductCategoriesAsync(System.Guid shopGuid) {
            return base.Channel.GetProductCategoriesAsync(shopGuid);
        }
        
        public OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto GetProductCategory(System.Guid productCategoryGuid) {
            return base.Channel.GetProductCategory(productCategoryGuid);
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto> GetProductCategoryAsync(System.Guid productCategoryGuid) {
            return base.Channel.GetProductCategoryAsync(productCategoryGuid);
        }
    }
}
