//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ShopRepositoryClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopDto", Namespace="https://online.catalog.com/")]
    [System.SerializableAttribute()]
    public partial class ShopDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlineCatalog.Web.Main.ShopRepositoryClient.UserAddressDto AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ShopGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineCatalog.Web.Main.ShopRepositoryClient.UserAddressDto Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ShopGuid {
            get {
                return this.ShopGuidField;
            }
            set {
                if ((this.ShopGuidField.Equals(value) != true)) {
                    this.ShopGuidField = value;
                    this.RaisePropertyChanged("ShopGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAddressDto", Namespace="https://onlinecatalog.com")]
    [System.SerializableAttribute()]
    public partial class UserAddressDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AddressGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AddressGuid {
            get {
                return this.AddressGuidField;
            }
            set {
                if ((this.AddressGuidField.Equals(value) != true)) {
                    this.AddressGuidField = value;
                    this.RaisePropertyChanged("AddressGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="ShopRepositoryClient.IShopRepositoryService")]
    public interface IShopRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetAllActiveShops", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetAllActiveShopsResponse")]
        OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto[] GetAllActiveShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetAllActiveShops", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetAllActiveShopsResponse")]
        System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto[]> GetAllActiveShopsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetShopByName", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetShopByNameResponse")]
        OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto GetShopByName(string shopName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetShopByName", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetShopByNameResponse")]
        System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto> GetShopByNameAsync(string shopName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetShopByUniqueId", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetShopByUniqueIdResponse")]
        OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto GetShopByUniqueId(System.Guid uniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopRepositoryService/GetShopByUniqueId", ReplyAction="https://online.catalog.com/IShopRepositoryService/GetShopByUniqueIdResponse")]
        System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto> GetShopByUniqueIdAsync(System.Guid uniqueId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopRepositoryServiceChannel : OnlineCatalog.Web.Main.ShopRepositoryClient.IShopRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopRepositoryServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ShopRepositoryClient.IShopRepositoryService>, OnlineCatalog.Web.Main.ShopRepositoryClient.IShopRepositoryService {
        
        public ShopRepositoryServiceClient() {
        }
        
        public ShopRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto[] GetAllActiveShops() {
            return base.Channel.GetAllActiveShops();
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto[]> GetAllActiveShopsAsync() {
            return base.Channel.GetAllActiveShopsAsync();
        }
        
        public OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto GetShopByName(string shopName) {
            return base.Channel.GetShopByName(shopName);
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto> GetShopByNameAsync(string shopName) {
            return base.Channel.GetShopByNameAsync(shopName);
        }
        
        public OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto GetShopByUniqueId(System.Guid uniqueId) {
            return base.Channel.GetShopByUniqueId(uniqueId);
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Web.Main.ShopRepositoryClient.ShopDto> GetShopByUniqueIdAsync(System.Guid uniqueId) {
            return base.Channel.GetShopByUniqueIdAsync(uniqueId);
        }
    }
}
