//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ProductAdministrationClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com", ConfigurationName="ProductAdministrationClient.IProductAdministrationService")]
    public interface IProductAdministrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductAdministrationService/AddProduct", ReplyAction="https://online.catalog.com/IProductAdministrationService/AddProductResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult AddProduct(OnlineCatalog.Common.DataContracts.Products.ProductDto product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductAdministrationService/EditProduct", ReplyAction="https://online.catalog.com/IProductAdministrationService/EditProductResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult EditProduct(OnlineCatalog.Common.DataContracts.Products.ProductDto product);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductAdministrationService/RemoveProduct", ReplyAction="https://online.catalog.com/IProductAdministrationService/RemoveProductResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult RemoveProduct(System.Guid productGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductAdministrationServiceChannel : OnlineCatalog.Web.Main.ProductAdministrationClient.IProductAdministrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductAdministrationServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ProductAdministrationClient.IProductAdministrationService>, OnlineCatalog.Web.Main.ProductAdministrationClient.IProductAdministrationService {
        
        public ProductAdministrationServiceClient() {
        }
        
        public ProductAdministrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductAdministrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAdministrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAdministrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult AddProduct(OnlineCatalog.Common.DataContracts.Products.ProductDto product) {
            return base.Channel.AddProduct(product);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult EditProduct(OnlineCatalog.Common.DataContracts.Products.ProductDto product) {
            return base.Channel.EditProduct(product);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult RemoveProduct(System.Guid productGuid) {
            return base.Channel.RemoveProduct(productGuid);
        }
    }
}
