using OnlineCatalog.Common.DataContracts.General;
using OnlineCatalog.Services.MailService.MessageBuilder.ConcreteMessageBuilders;

namespace OnlineCatalog.Services.MailService.MessageBuilder
{
    public class MessageBuilderFactory : IMessageBuilderFactory
    {
        public IMessageBuilder CreateMessageBuilder(MailMessageType messageType)
        {
            if(messageType == MailMessageType.Registration) return new RegisterMessageBuilder();
            return new AutoGeneratedEmailWithDefaultContent();
        }
    }
}