//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.UserAssignmentClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="UserAssignmentClient.IUserAssignmentService")]
    public interface IUserAssignmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IUserAssignmentService/AssignUserToShop", ReplyAction="https://online.catalog.com/IUserAssignmentService/AssignUserToShopResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult AssignUserToShop(System.Guid userGuid, System.Guid shopGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IUserAssignmentService/UnassignUserFromShop", ReplyAction="https://online.catalog.com/IUserAssignmentService/UnassignUserFromShopResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult UnassignUserFromShop(System.Guid userGuid, System.Guid shopGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAssignmentServiceChannel : OnlineCatalog.Web.Main.UserAssignmentClient.IUserAssignmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAssignmentServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.UserAssignmentClient.IUserAssignmentService>, OnlineCatalog.Web.Main.UserAssignmentClient.IUserAssignmentService {
        
        public UserAssignmentServiceClient() {
        }
        
        public UserAssignmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAssignmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAssignmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAssignmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult AssignUserToShop(System.Guid userGuid, System.Guid shopGuid) {
            return base.Channel.AssignUserToShop(userGuid, shopGuid);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult UnassignUserFromShop(System.Guid userGuid, System.Guid shopGuid) {
            return base.Channel.UnassignUserFromShop(userGuid, shopGuid);
        }
    }
}
