//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Services.RegistrationService.MailServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailServiceClient.IMailService")]
    public interface IMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="SendMail", ReplyAction="http://tempuri.org/IMailService/SendMailResponse")]
        void SendMail(OnlineCatalog.Common.DataContracts.General.MailContext context);
        
        [System.ServiceModel.OperationContractAttribute(Action="BuildMessage", ReplyAction="http://tempuri.org/IMailService/BuildMessageResponse")]
        OnlineCatalog.Common.DataContracts.General.MailContext BuildMessage(OnlineCatalog.Common.DataContracts.General.MailContext messageType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceChannel : OnlineCatalog.Services.RegistrationService.MailServiceClient.IMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Services.RegistrationService.MailServiceClient.IMailService>, OnlineCatalog.Services.RegistrationService.MailServiceClient.IMailService {
        
        public MailServiceClient() {
        }
        
        public MailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMail(OnlineCatalog.Common.DataContracts.General.MailContext context) {
            base.Channel.SendMail(context);
        }
        
        public OnlineCatalog.Common.DataContracts.General.MailContext BuildMessage(OnlineCatalog.Common.DataContracts.General.MailContext messageType) {
            return base.Channel.BuildMessage(messageType);
        }
    }
}
