//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ProductRepositoryClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="ProductRepositoryClient.IProductRepositoryService")]
    public interface IProductRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductRepositoryService/GetShopProducts", ReplyAction="https://online.catalog.com/IProductRepositoryService/GetShopProductsResponse")]
        OnlineCatalog.Common.DataContracts.Products.ProductDto[] GetShopProducts(System.Guid shopGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductRepositoryService/GetProduct", ReplyAction="https://online.catalog.com/IProductRepositoryService/GetProductResponse")]
        OnlineCatalog.Common.DataContracts.Products.ProductDto GetProduct(System.Guid productGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductRepositoryServiceChannel : OnlineCatalog.Web.Main.ProductRepositoryClient.IProductRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductRepositoryServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ProductRepositoryClient.IProductRepositoryService>, OnlineCatalog.Web.Main.ProductRepositoryClient.IProductRepositoryService {
        
        public ProductRepositoryServiceClient() {
        }
        
        public ProductRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.Products.ProductDto[] GetShopProducts(System.Guid shopGuid) {
            return base.Channel.GetShopProducts(shopGuid);
        }
        
        public OnlineCatalog.Common.DataContracts.Products.ProductDto GetProduct(System.Guid productGuid) {
            return base.Channel.GetProduct(productGuid);
        }
    }
}
