//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ProductCategoryServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="ProductCategoryServiceClient.IProductCategoryService")]
    public interface IProductCategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryService/AddProductCategory", ReplyAction="https://online.catalog.com/IProductCategoryService/AddProductCategoryResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult AddProductCategory(OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto productCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryService/RemoveProductCategory", ReplyAction="https://online.catalog.com/IProductCategoryService/RemoveProductCategoryResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult RemoveProductCategory(System.Guid productCategoryUniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IProductCategoryService/EditProductCategory", ReplyAction="https://online.catalog.com/IProductCategoryService/EditProductCategoryResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult EditProductCategory(OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto productCategory);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCategoryServiceChannel : OnlineCatalog.Web.Main.ProductCategoryServiceClient.IProductCategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCategoryServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ProductCategoryServiceClient.IProductCategoryService>, OnlineCatalog.Web.Main.ProductCategoryServiceClient.IProductCategoryService {
        
        public ProductCategoryServiceClient() {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult AddProductCategory(OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto productCategory) {
            return base.Channel.AddProductCategory(productCategory);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult RemoveProductCategory(System.Guid productCategoryUniqueId) {
            return base.Channel.RemoveProductCategory(productCategoryUniqueId);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult EditProductCategory(OnlineCatalog.Common.DataContracts.Products.ProductCategoryDto productCategory) {
            return base.Channel.EditProductCategory(productCategory);
        }
    }
}
