//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.BasketRepositoryClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="BasketRepositoryClient.IBasketRepositoryService")]
    public interface IBasketRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IBasketRepositoryService/GetBasketByUniqueId", ReplyAction="https://online.catalog.com/IBasketRepositoryService/GetBasketByUniqueIdResponse")]
        OnlineCatalog.Common.DataContracts.Orders.BasketDto GetBasketByUniqueId(System.Guid uniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IBasketRepositoryService/GetShopBasketForClient", ReplyAction="https://online.catalog.com/IBasketRepositoryService/GetShopBasketForClientRespons" +
            "e")]
        OnlineCatalog.Common.DataContracts.Orders.BasketDto GetShopBasketForClient(System.Guid shopGuid, string clientLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IBasketRepositoryService/GetBaskets", ReplyAction="https://online.catalog.com/IBasketRepositoryService/GetBasketsResponse")]
        OnlineCatalog.Common.DataContracts.Orders.BasketDto[] GetBaskets(System.Guid shopGUid, string clientLogin, OnlineCatalog.Common.DataContracts.Orders.OrderState[] orderStates);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasketRepositoryServiceChannel : OnlineCatalog.Web.Main.BasketRepositoryClient.IBasketRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasketRepositoryServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.BasketRepositoryClient.IBasketRepositoryService>, OnlineCatalog.Web.Main.BasketRepositoryClient.IBasketRepositoryService {
        
        public BasketRepositoryServiceClient() {
        }
        
        public BasketRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasketRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasketRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasketRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.Orders.BasketDto GetBasketByUniqueId(System.Guid uniqueId) {
            return base.Channel.GetBasketByUniqueId(uniqueId);
        }
        
        public OnlineCatalog.Common.DataContracts.Orders.BasketDto GetShopBasketForClient(System.Guid shopGuid, string clientLogin) {
            return base.Channel.GetShopBasketForClient(shopGuid, clientLogin);
        }
        
        public OnlineCatalog.Common.DataContracts.Orders.BasketDto[] GetBaskets(System.Guid shopGUid, string clientLogin, OnlineCatalog.Common.DataContracts.Orders.OrderState[] orderStates) {
            return base.Channel.GetBaskets(shopGUid, clientLogin, orderStates);
        }
    }
}
