//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.ShopConfigurationClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://online.catalog.com/", ConfigurationName="ShopConfigurationClient.IShopConfigurationService")]
    public interface IShopConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopConfigurationService/AddNewShop", ReplyAction="https://online.catalog.com/IShopConfigurationService/AddNewShopResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult AddNewShop(OnlineCatalog.Common.DataContracts.Groups.ShopDto shop);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopConfigurationService/ShopActivation", ReplyAction="https://online.catalog.com/IShopConfigurationService/ShopActivationResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult ShopActivation(System.Guid shopGuid, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://online.catalog.com/IShopConfigurationService/EditShop", ReplyAction="https://online.catalog.com/IShopConfigurationService/EditShopResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult EditShop(OnlineCatalog.Common.DataContracts.Groups.ShopDto shop);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopConfigurationServiceChannel : OnlineCatalog.Web.Main.ShopConfigurationClient.IShopConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopConfigurationServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.ShopConfigurationClient.IShopConfigurationService>, OnlineCatalog.Web.Main.ShopConfigurationClient.IShopConfigurationService {
        
        public ShopConfigurationServiceClient() {
        }
        
        public ShopConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult AddNewShop(OnlineCatalog.Common.DataContracts.Groups.ShopDto shop) {
            return base.Channel.AddNewShop(shop);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult ShopActivation(System.Guid shopGuid, bool isActive) {
            return base.Channel.ShopActivation(shopGuid, isActive);
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult EditShop(OnlineCatalog.Common.DataContracts.Groups.ShopDto shop) {
            return base.Channel.EditShop(shop);
        }
    }
}
