//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCatalog.Web.Main.RegistrationClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://online.catalog.com", ConfigurationName="RegistrationClient.IRegisterService")]
    public interface IRegisterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="RegisterUser", ReplyAction="http://online.catalog.com/IRegisterService/RegisterUserResponse")]
        OnlineCatalog.Common.DataContracts.ServiceActionResult RegisterUser(OnlineCatalog.Common.DataContracts.Administration.UserDto userForRegistration);
        
        [System.ServiceModel.OperationContractAttribute(Action="RegisterUser", ReplyAction="http://online.catalog.com/IRegisterService/RegisterUserResponse")]
        System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.ServiceActionResult> RegisterUserAsync(OnlineCatalog.Common.DataContracts.Administration.UserDto userForRegistration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterServiceChannel : OnlineCatalog.Web.Main.RegistrationClient.IRegisterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterServiceClient : System.ServiceModel.ClientBase<OnlineCatalog.Web.Main.RegistrationClient.IRegisterService>, OnlineCatalog.Web.Main.RegistrationClient.IRegisterService {
        
        public RegisterServiceClient() {
        }
        
        public RegisterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OnlineCatalog.Common.DataContracts.ServiceActionResult RegisterUser(OnlineCatalog.Common.DataContracts.Administration.UserDto userForRegistration) {
            return base.Channel.RegisterUser(userForRegistration);
        }
        
        public System.Threading.Tasks.Task<OnlineCatalog.Common.DataContracts.ServiceActionResult> RegisterUserAsync(OnlineCatalog.Common.DataContracts.Administration.UserDto userForRegistration) {
            return base.Channel.RegisterUserAsync(userForRegistration);
        }
    }
}
