using OnlineCatalog.Common.DataContracts.General;

namespace OnlineCatalog.Services.MailService.MessageBuilder.ConcreteMessageBuilders
{
    public class AutoGeneratedEmailWithDefaultContent : MessageBuilder, IMessageBuilder
    {
        public string BuildMessageContent(MailContext context)
        {
            _stringBuilder.Append(context.EmailContent.MessageBody);
            Finalize();
            return _stringBuilder.ToString();
        }
    }
}