using OnlineCatalog.Common.DataContracts.General;

namespace OnlineCatalog.Services.MailService.MessageBuilder.ConcreteMessageBuilders
{
    public class RegisterMessageBuilder : MessageBuilder, IMessageBuilder
    {
        public string BuildMessageContent(MailContext context)
        {
            _stringBuilder.AppendFormat("Thank you {0} for your registration. Below you can find autogenerated link which you should use to confirm your registration", context.EmailContent.ReceiverName);
            Finalize();

            return _stringBuilder.ToString();
        }
    }
}